/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesRoiCalculatorRouteImport } from './routes/resources/roi-calculator'
import { Route as ResourcesImplementationChecklistRouteImport } from './routes/resources/implementation-checklist'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as ProposalRouteImport } from './routes/proposal.'
import { Route as AdminProposalsNewRouteImport } from './routes/admin/proposals/new'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoiCalculatorRoute = ResourcesRoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesImplementationChecklistRoute =
  ResourcesImplementationChecklistRouteImport.update({
    id: '/implementation-checklist',
    path: '/implementation-checklist',
    getParentRoute: () => ResourcesRoute,
  } as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalRoute = ProposalRouteImport.update({
  id: '/proposal/',
  path: '/proposal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProposalsNewRoute = AdminProposalsNewRouteImport.update({
  id: '/admin/proposals/new',
  path: '/admin/proposals/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRoute
  '/demo': typeof DemoRoute
  '/founder': typeof FounderRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/proposal/': typeof ProposalRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/resources/implementation-checklist': typeof ResourcesImplementationChecklistRoute
  '/resources/roi-calculator': typeof ResourcesRoiCalculatorRoute
  '/admin/proposals/new': typeof AdminProposalsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRoute
  '/demo': typeof DemoRoute
  '/founder': typeof FounderRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/proposal': typeof ProposalRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/resources/implementation-checklist': typeof ResourcesImplementationChecklistRoute
  '/resources/roi-calculator': typeof ResourcesRoiCalculatorRoute
  '/admin/proposals/new': typeof AdminProposalsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRoute
  '/demo': typeof DemoRoute
  '/founder': typeof FounderRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/proposal/': typeof ProposalRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/resources/implementation-checklist': typeof ResourcesImplementationChecklistRoute
  '/resources/roi-calculator': typeof ResourcesRoiCalculatorRoute
  '/admin/proposals/new': typeof AdminProposalsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessment'
    | '/blog'
    | '/contact'
    | '/crm'
    | '/demo'
    | '/founder'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/security'
    | '/services'
    | '/terms'
    | '/proposal/'
    | '/admin/leads'
    | '/resources/implementation-checklist'
    | '/resources/roi-calculator'
    | '/admin/proposals/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessment'
    | '/blog'
    | '/contact'
    | '/crm'
    | '/demo'
    | '/founder'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/security'
    | '/services'
    | '/terms'
    | '/proposal'
    | '/admin/leads'
    | '/resources/implementation-checklist'
    | '/resources/roi-calculator'
    | '/admin/proposals/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assessment'
    | '/blog'
    | '/contact'
    | '/crm'
    | '/demo'
    | '/founder'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/security'
    | '/services'
    | '/terms'
    | '/proposal/'
    | '/admin/leads'
    | '/resources/implementation-checklist'
    | '/resources/roi-calculator'
    | '/admin/proposals/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssessmentRoute: typeof AssessmentRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CrmRoute: typeof CrmRoute
  DemoRoute: typeof DemoRoute
  FounderRoute: typeof FounderRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  ProposalRoute: typeof ProposalRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminProposalsNewRoute: typeof AdminProposalsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/roi-calculator': {
      id: '/resources/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/resources/roi-calculator'
      preLoaderRoute: typeof ResourcesRoiCalculatorRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/implementation-checklist': {
      id: '/resources/implementation-checklist'
      path: '/implementation-checklist'
      fullPath: '/resources/implementation-checklist'
      preLoaderRoute: typeof ResourcesImplementationChecklistRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/': {
      id: '/proposal/'
      path: '/proposal'
      fullPath: '/proposal/'
      preLoaderRoute: typeof ProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/proposals/new': {
      id: '/admin/proposals/new'
      path: '/admin/proposals/new'
      fullPath: '/admin/proposals/new'
      preLoaderRoute: typeof AdminProposalsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesImplementationChecklistRoute: typeof ResourcesImplementationChecklistRoute
  ResourcesRoiCalculatorRoute: typeof ResourcesRoiCalculatorRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesImplementationChecklistRoute: ResourcesImplementationChecklistRoute,
  ResourcesRoiCalculatorRoute: ResourcesRoiCalculatorRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssessmentRoute: AssessmentRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CrmRoute: CrmRoute,
  DemoRoute: DemoRoute,
  FounderRoute: FounderRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  ProposalRoute: ProposalRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminProposalsNewRoute: AdminProposalsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
